Resolve muiltithreading issues around EnvHelper singleton
- We're occasionally seeing the below error when ingesting:
```
Exception while executing function: Functions.batch_push_results Result: Failure
Exception: AttributeError: 'EnvHelper' object has no attribute 'AZURE_BLOB_ACCOUNT_NAME'
Stack:   File "/azure-functions-host/workers/python/3.11/LINUX/X64/azure_functions_worker/dispatcher.py", line 505, in _handle__invocation_request
    call_result = await self._loop.run_in_executor(
has context menu
```
- I believe this is caused by multiple threads running at the same time
  - The first one creates the instance and starts populating the config
  - The second sees the instance the first one has created, but tries to
    use it before the config has been populated
- This change wraps the code in a lock to ensure only one thread at a
  time can get an instance of the EnvHelper